e(nil . ((cider-clojure-cli-parameters         . "-A:dev:test:build")
         ;; (cider-preferred-build-tool        . clojure-cli)
         (cider-redirect-server-output-to-repl . t)
         (cider-repl-display-help-banner       . nil)
         (clojure-toplevel-inside-comment-form . t)
         (cider-custom-clj-repl-init-form      . "(go)")
         ;; (cider-repl-init-code              . ("(go)"))
         (cider-default-cljs-repl              . shadow)
         (cider-shadow-default-options         . ":app"))))
