# This file creates a keys for github to be able to deploy 03-lambda.yml
---
AWSTemplateFormatVersion: '2010-09-09'

Resources:
  GithubDeployUser:
    Type: 'AWS::IAM::User'
    Properties:
      Policies:
        - PolicyName: lambda
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - lambda:*
                Resource: !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:*"
        - PolicyName: ssm-parameter-get
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ssm:Describe*
                  - ssm:Get*
                  - ssm:List*
                Resource: !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/xt-play_*"
        - PolicyName: s3
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObjectVersion
                Resource:
                  - arn:aws:s3:::xt-play-lambda-code
                  - arn:aws:s3:::xt-play-lambda-code/*
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:ListBucket
                Resource:
                  - arn:aws:s3:::xtdb-play-datasets
                  - arn:aws:s3:::xtdb-play-datasets/*
        # https://github.com/aws-actions/aws-cloudformation-github-deploy?tab=readme-ov-file#permissions
        - PolicyName: cloudformation-deploy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - cloudformation:CreateStack
                  - cloudformation:DescribeStacks
                  - cloudformation:CreateChangeSet
                  - cloudformation:DescribeChangeSet
                  - cloudformation:DeleteChangeSet
                  - cloudformation:ExecuteChangeSet
                Resource: "*"
        - PolicyName: pass-lambda-role
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - iam:PassRole
                Resource: !Sub "arn:aws:iam::${AWS::AccountId}:role/xt-play-lambda-deps-LambdaExecutionRole-*"


  GithubDeployUserAccessKey:
    Type: 'AWS::IAM::AccessKey'
    Properties:
      UserName: !Ref GithubDeployUser

Outputs:
  GithubDeployAccessKeyId:
    Value: !Ref GithubDeployUserAccessKey
  GithubDeploySecretAccessKey:
    Value: !GetAtt GithubDeployUserAccessKey.SecretAccessKey
