# This file hooks up the lambda function url to CloudFront
---
AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  HostedZoneId:
    Type: 'String'
    Description: 'The zone id for the hosted zone'
  HostedZoneName:
    Type: 'String'
    Description: 'The zone name for the hosted zone'
  CertificateArn:
    Type: 'String'
    Description: 'The arn of the certificate'

Resources:
  PlayCloudFront:
    Type: 'AWS::CloudFront::Distribution'
    Properties:
      DistributionConfig:
        Enabled: true
        Origins:
          - Id: LambdaOrigin
            DomainName: '{{resolve:ssm:xt-play_play-lambda-url-function-url-domain}}'
            CustomOriginConfig:
              OriginProtocolPolicy: https-only
        DefaultCacheBehavior:
          TargetOriginId: LambdaOrigin
          AllowedMethods: [GET, HEAD, POST, PUT, PATCH, OPTIONS, DELETE]
          ViewerProtocolPolicy: redirect-to-https
          # https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/using-managed-cache-policies.html#managed-cache-policy-caching-disabled
          CachePolicyId: '4135ea2d-6df8-44a3-9df3-4b5a84be39ad'
          # https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/using-managed-origin-request-policies.html#managed-origin-request-policy-all-viewer-except-host-header
          OriginRequestPolicyId: 'b689b0a8-53d0-40ab-baf2-68738e2966ac'
        Aliases:
          - !Sub
            - 'play.${Domain}'
            - Domain: !Ref HostedZoneName
        ViewerCertificate:
          AcmCertificateArn: !Ref CertificateArn
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1

  PlayDomainRecord:
    Type: 'AWS::Route53::RecordSet'
    Properties:
      Name: !Sub
        - 'play.${Domain}.'
        - Domain: !Ref HostedZoneName
      HostedZoneId: !Ref HostedZoneId
      Type: 'A'
      AliasTarget:
        DNSName: !GetAtt PlayCloudFront.DomainName
        # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-recordset-aliastarget.html#cfn-route53-recordset-aliastarget-hostedzoneid
        HostedZoneId: 'Z2FDTNDATAQYW2'
        EvaluateTargetHealth: false

  KeepLambdaWarmTrigger:
    Type: AWS::Events::Rule
    Properties:
      Description: "ScheduledRule"
      ScheduleExpression: "rate(15 minutes)"
      State: "ENABLED"
      Targets:
        - Arn: '{{resolve:ssm:xt-play_play-lambda-alias-arn}}'
          Id: "TargetFunctionV1"

  PermissionForEventsToInvokeLambda:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: '{{resolve:ssm:xt-play_play-lambda-name}}'
      Action: "lambda:InvokeFunction"
      Principal: "events.amazonaws.com"
      SourceArn: !GetAtt KeepLambdaWarmTrigger.Arn
