---
AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  DockerTag:
    Type: 'String'
    Default: 'latest'
    Description: 'The zone name for the hosted zone'

Resources:
  # TODO: Add scaling
  TaskDefinition:
    Type: 'AWS::ECS::TaskDefinition'
    Properties:
      Family: 'xt-fiddle'
      RequiresCompatibilities:
        - 'FARGATE'
      NetworkMode: 'awsvpc'

      # TODO: Scale up/down?
      Cpu: '1024'
      Memory: '4096'
      ExecutionRoleArn: '{{resolve:ssm:xt-fiddle_task-execution-role-arn}}'
      TaskRoleArn: '{{resolve:ssm:xt-fiddle_task-role-arn}}'

      ContainerDefinitions:
        - Name: 'xt-fiddle'
          Image: !Join [":", ['{{resolve:ssm:xt-fiddle_container-repo-repo-uri}}', !Ref DockerTag]]
          Essential: true
          PortMappings:
            - ContainerPort: 8000
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: '{{resolve:ssm:xt-fiddle_log-group}}'
              awslogs-region: !Ref 'AWS::Region'
              awslogs-stream-prefix: xt-fiddle

  ECSService:
    Type: 'AWS::ECS::Service'
    Properties:
      Cluster: '{{resolve:ssm:xt-fiddle_ecs-cluster}}'
      TaskDefinition: !Ref TaskDefinition
      LaunchType: 'FARGATE'

      DesiredCount: 1
      HealthCheckGracePeriodSeconds: 120

      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: 'DISABLED'
          SecurityGroups:
            - '{{resolve:ssm:xt-fiddle_task-security-group}}'
          Subnets:
            - '{{resolve:ssm:xt-fiddle_private-subnet-1}}'
            - '{{resolve:ssm:xt-fiddle_private-subnet-2}}'
      LoadBalancers:
        - ContainerName: xt-fiddle
          ContainerPort: '8000'
          TargetGroupArn: '{{resolve:ssm:xt-fiddle_target-group-arn}}'

  SSMECSService:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Name: 'xt-fiddle_ecs-service-arn'
      Value: !Ref ECSService
